# 🔹 Why NumPy when we already have Python Lists?

Python provides **lists**, which can store multiple values.  
So why do we need **NumPy arrays**?

---

## ✅ Limitations of Python Lists
1. **Performance Issues**  
   - Lists are slow for mathematical computations.  
   - Operations require Python loops → inefficient for large datasets.

2. **Memory Inefficiency**  
   - Lists store objects with extra metadata → more memory usage.  
   - Example: `list = [1, 2, 3]` stores integers + object pointers.

3. **No Vectorization**  
   - Lists don’t support element-wise operations directly.  
   - Example:
     ```python
     a = [1, 2, 3]
     b = [4, 5, 6]
     print(a + b)  # Just concatenates → [1,2,3,4,5,6]
     ```
   - For mathematical operations, we need loops or list comprehensions.

4. **Limited Functionality**  
   - Lists don’t have built-in methods for advanced math/statistics.  
   - Example: mean, median, standard deviation → must be coded manually.

---

## ✅ Why NumPy is Better

1. **Faster Execution**  
   - Written in **C** → operations are highly optimized.  
   - Uses **vectorization** (no explicit loops required).

2. **Less Memory Usage**  
   - Stores data in a contiguous block (fixed type, e.g., int32).  
   - Much more efficient than Python lists.

3. **Supports Vectorized Operations**  
   - Example:
     ```python
     import numpy as np
     a = np.array([1, 2, 3])
     b = np.array([4, 5, 6])
     print(a + b)   # [5 7 9]
     print(a * b)   # [ 4 10 18]
     ```

4. **Rich Mathematical Functions**  
   - Mean, median, variance, trigonometry, linear algebra, etc.  
   - Example:
     ```python
     np.mean(a)   # 2.0
     np.std(a)    # 0.816...
     ```

5. **Multi-dimensional Arrays**  
   - NumPy supports matrices & n-dimensional arrays.  
   - Lists are only 1D (nested lists get messy).

---

## ✅ Example: Speed Test

```python
import numpy as np
import time

# Python list
lst = list(range(1000000))
start = time.time()
sum_lst = [x**2 for x in lst]   # Square using loop
end = time.time()
print("Python List Time:", end - start)

# NumPy array
arr = np.arange(1000000)
start = time.time()
sum_arr = arr**2   # Vectorized operation
end = time.time()
print("NumPy Array Time:", end - start)


# 🔹 Difference Between Python List and NumPy Array

| Feature                   | Python List                                | NumPy Array                               |
|----------------------------|-------------------------------------------|-------------------------------------------|
| Data Type                  | Can hold **heterogeneous** elements        | Mostly **homogeneous** elements           |
| Performance                | Slower for large-scale numeric operations | Fast due to **C implementation & vectorization** |
| Memory Usage               | Higher (stores extra info for objects)    | Lower (contiguous memory block)          |
| Mathematical Operations    | Element-wise operations need loops        | Supports **vectorized operations** (`+`, `-`, `*`, `/`) |
| Multi-dimensional Support  | Nested lists (less efficient)             | Built-in n-dimensional arrays (`ndarray`) |
| Functionality              | Limited (basic methods)                   | Rich mathematical & statistical functions |
| Indexing                   | Integer-based                              | Integer & boolean-based indexing, slicing |
| Missing Data               | Must handle manually                        | Can handle NaN with floating type         |
| Use Case                   | General-purpose storage                     | Scientific computing, ML, AI, data analysis |

---

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# dimension and scale of Array
arr.ndim

1

In [11]:
a=np.array([[[]]])
a.ndim
a.shape

(1, 1, 0)

In [12]:
# creating a range of number

range=np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# creating range By giving start Stop and step value

range =np.arange(1,10,2) #start , stop , step
range


array([1, 3, 5, 7, 9])

# 🔹 Using `numpy.linspace()`

`numpy.linspace(start, stop, num)` is used to **create evenly spaced numbers over a specified interval**.

- `start` → starting value of the sequence  
- `stop` → end value of the sequence (inclusive by default)  
- `num` → number of samples to generate (default is 50)  

---

## Example: linspace from 0 to 1 with 10 numbers
```python





In [15]:
# using linspace (0,1,10)
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# logspace 

- np.logspace(start,ending -> power value, number of values in the scale)

In [19]:
arr= np.logspace(1,3,2)
# logarithmic scale array->10^1 ->10^3 .. 3 points
arr

array([  10., 1000.])

In [20]:
arr= np.logspace(1,3,5)
# logarithmic scale array->10^1 ->10^3 .. 3 points
arr

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

## np.zeros
- It will create an array full of zeros

In [21]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

## np.ones
- It will create an arr full of one

In [22]:
arr =np.ones([4,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## np.full
- it will create the array with any constant value


In [23]:
arr=np.full(10,2) # -.create an array full of any value

arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# creating 2d array
arr= np.full([2,4],8) #[row,column],default value
arr

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
arr=np.empty([2,3]) #Uninitialized array
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.random.rand() 
- generating Random floats 
-

In [27]:
arr=np.random.rand(2,3)
arr

array([[0.01091142, 0.36154778, 0.00431531],
       [0.45560047, 0.92731651, 0.25504025]])

In [29]:
arr=np.random.randn(2,3) # ->random float from standard normal distribution 
arr

array([[ 1.27126155,  0.06973022,  0.14265458],
       [-0.48159273, -0.26475609,  0.04500287]])

In [31]:
arr=np.random.randint(10,100,size=(2,3)) # -> start ,stop ,dimension/number of values
arr #-> random integers

array([[50, 22, 23],
       [27, 88, 20]])

# Numpy Data Type and Type Casting

In [33]:
arr =np.array([1,2,3.1,4,5,6])
arr

array([1. , 2. , 3.1, 4. , 5. , 6. ])

In [34]:
print(type(arr))

<class 'numpy.ndarray'>


In [35]:
lst=["String ",'1','2','5']
arr=np.array(lst)
arr

array(['String ', '1', '2', '5'], dtype='<U7')

In [40]:
arr=np.array([1,2,3,4,5],dtype=np.float64)

arr

array([1., 2., 3., 4., 5.])

In [39]:
arr.dtype

dtype('float64')

In [41]:
# type casting -> astype()
arr=np.array([1,2,3])
arr.dtype

dtype('int32')

In [42]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

reshaped = arr.reshape(3,3)
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# revel ->convery 1D array

revel =reshaped.ravel()
revel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Arithmetic Operations On Arrays

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [12]:
print(a+b)

[5 7 9]


In [13]:
# print(a-b)
print(a-b)

[-3 -3 -3]


In [14]:
# division 
print(a/b)

[0.25 0.4  0.5 ]


In [15]:
# exonent-> power
print(a**2)

[1 4 9]


# universal Fuction ->ufuncs

In [ ]:
# square Root 
arr=np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [18]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [20]:
angeles =np.array([0,np.pi,np.pi/2])
print(np.sin(angeles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


## Indexing and Slicing

In [ ]:
a=[213,324,4524,564,765,45]

In [21]:
# if you not provide step value the  nodata will be show
a[-1:-4:-1]

array([3, 2, 1])

In [ ]:
# without step value
a[-1:-4]

array([], dtype=int32)

In [23]:
a[::2]

array([1, 3])

In [24]:
arr=np.array([10,20,30,40,50])
# indexes=0,2,4
arr[::2]

array([10, 30, 50])

In [27]:
# negative indixng to access last element of the numpy array
arr[-1]

50

In [28]:
print(arr[-1])

50


In [32]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [34]:
print(matrix[1: ,1:])

[[5 6]
 [8 9]]


# Index arrays->Advance Indexing

In [35]:
#np.take-> built in function to perform indexing and slicing 
arr=np.array([10,20,30,40,50,])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


# Iterating with nditer()

In [ ]:
arr =np.array([[1,2],[3,4]])

In [36]:
for x in np.nditer(arr):
    print(x,end=" ")

10 20 30 40 50 

In [37]:
# ndenumerate( )-> both index +value

for ind, x in np.ndenumerate(arr):
    print(ind,x)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50


In [38]:
# Views vs Copies

arr=np.array([1,2,3,4,5])
view =arr[1:3]
view

array([2, 3])

In [40]:
# modifying the array 
copy=view[0]=200

arr

array([  1, 200,   3,   4,   5])

In [42]:
# copy
copy=arr[1:3].copy()
copy

array([200,   3])

In [ ]:
# the values arr unchanged
arr

array([  1, 200,   3,   4,   5])

In [45]:
# Transpose of a matrix
print(arr.transpose())

[  1 200   3   4   5]


In [46]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [47]:
print(arr.transpose())

[[1 3]
 [2 4]]


# Swapaxes->swap 2 specific axes in a matrix


In [48]:
arr=np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [49]:
swap=np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [ ]:
# concatenation:
a=np.array([1,2])
b=np.array([3,4])

In [50]:
combine =np.concatenate((a,b))
combine

array([1, 2, 3, 4, 5, 6])

In [56]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])

In [60]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [58]:
print(np.hstack((arr1,arr2)))

[[1 2 1 2]
 [3 4 3 4]]


In [63]:
print(np.stack((arr1,arr2), axis=0))

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [64]:
print(np.stack((arr1,arr2), axis=1))

[[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]]


In [67]:
# spliting the arr
print(np.split(arr1,2))

[array([[1, 2]]), array([[3, 4]])]


In [68]:
# repealt will going to repeat the array n number of time
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3 4 4 4]


In [72]:
arr

array([[[1, 2],
        [3, 4]]])

In [73]:
# title -> repeat my whole array
print(np.tile([1,2,4,5,6,7,8],2))

[1 2 4 5 6 7 8 1 2 4 5 6 7 8]


In [74]:
# Aggregate Functions:

arr =np.array([1,2,3])
print(np.sum(arr))

6


In [75]:
np.mean(arr)

2.0

In [ ]:
# standerd daviation 
np.std(arr)

0.816496580927726

In [77]:
np.var(arr)

0.6666666666666666

In [78]:
np.min(arr)

1

In [79]:
print(np.sum(matrix,axis=0))

[12 15 18]


In [80]:
# Cumulative Operations-> running total

arr

array([1, 2, 3])

In [81]:
print(np.cumsum(arr))

[1 3 6]


In [83]:
# Where :
arr

array([1, 2, 3])

In [84]:
result =np.where(arr<2,"low","high")

In [85]:
result

array(['low', 'high', 'high'], dtype='<U4')